backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "public/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img"
collections:
  - name: "about"
    label: "About Page"
    folder: "public/content/about"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image (must be sized 200x200px)", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}